### ISSUE TITLE
Repeated File Extensions

### ISSUE THREAD

**Issue by Kronostheus** [eden-box/pdfworkshop#1]
Issue found when running tool through batches to avoid API issues. When the output directory already contains files from previous runs, tool will rename all files in the directory with '.pdf' extension. This causes files from previous runs, ex: "Lab01.pdf", to be renamed as "Lab01.pdf.pdf".

**Comment by sinistro14** [comment]
Closed with 3fdaf96efde2799e86dbf6510bf4a0346bc8997c
